"""Adapt the sto-rag STO chapter into this project's document schema.

The STO chapter (Korean token-security legal reference, generated by the sibling
sto-rag project) uses domain-view roles {general, legal, engineer}. This repo enforces
permission with the 6-rule engine keyed on `sensitivity` (permission/rules.py), so the
STO view-tiers are mapped onto the sensitivity axis:

    view:general / view:legal  → sensitivity: public    (public statutory reference)
    view:engineer              → sensitivity: internal   (internal engineering commentary)

STO documents are `legal.regulatory` / `legal.opinion`, which parties_rule abstains on
(LEGAL_SUBTYPES = contract/litigation only), so they fall through to sensitivity_rule —
exactly the intended gate. `expected_readers` is set to the roles sensitivity_rule grants
(oracle consistency with the BWCorp fixture).

Usage:
    python scripts/adapt_sto_chapter.py [SOURCE_CHAPTER_YAML] [OUT_YAML]
    # default SOURCE: ../sto-rag-main/data/sto_permission_chapter.yaml
    # default OUT:    data/sto_chapter.yaml
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SRC = _ROOT.parent / "sto-rag-main" / "data" / "sto_permission_chapter.yaml"
DEFAULT_OUT = _ROOT / "data" / "sto_chapter.yaml"

# Roles sensitivity_rule grants each level (see permission/rules.py ROLE_DEFAULTS).
PUBLIC_READERS = ["employee", "team_lead", "executive", "security_officer",
                  "hr_specialist", "contractor"]
INTERNAL_READERS = ["team_lead", "executive", "security_officer", "hr_specialist"]

_CORE = ("id", "title", "category", "sub_type", "sensitivity", "language",
         "body", "expected_readers", "tags")


def adapt_doc(d: dict) -> dict:
    tier = d["tags"][2].split(":", 1)[1]          # general | legal | engineer
    sensitivity = "internal" if tier == "engineer" else "public"
    readers = INTERNAL_READERS if sensitivity == "internal" else PUBLIC_READERS
    return {
        "id": d["id"],
        "title": d["title"],
        "category": "legal",
        "sub_type": d["sub_type"],               # legal.regulatory | legal.opinion
        "sensitivity": sensitivity,
        "language": d.get("language", "ko"),
        "body": d["body"],
        "expected_readers": list(readers),
        "tags": ["sto", d["tags"][1]],           # provenance: sto marker + source chunk id
    }


def main() -> int:
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SRC
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_OUT
    if not src.exists():
        print(f"source chapter not found: {src}")
        return 1

    docs = yaml.safe_load(src.read_text(encoding="utf-8"))["documents"]
    adapted = [adapt_doc(d) for d in docs]

    from collections import Counter
    sens = Counter(d["sensitivity"] for d in adapted)

    header = (
        "# STO chapter — adapted from sto-rag into this project's document schema.\n"
        "# Generated by scripts/adapt_sto_chapter.py. STO view-tiers mapped to\n"
        "# sensitivity: general/legal -> public, engineer -> internal.\n\n"
    )
    out.write_text(
        header + yaml.safe_dump({"documents": adapted}, allow_unicode=True,
                                sort_keys=False, width=100),
        encoding="utf-8",
    )
    print(f"wrote {len(adapted)} STO documents -> {out}")
    print(f"sensitivity: {dict(sens)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
